In [1]:
import pandas as pd

In [ ]:
club_standard_stats = pd.read_csv(r"C:\Users\salma\Downloads\Club_Stats.csv")
domestic_league= pd.read_csv(r"C:\Users\salma\Downloads\Domestic_leagues.csv")
domestic_cup= pd.read_csv(r"C:\Users\salma\Downloads\Domestic_cups.csv")
international_cups = pd.read_csv(r"C:\Users\salma\Downloads\International_cups.csv")
national_team = pd.read_csv(r"C:\Users\salma\Downloads\National_Team.csv")

#shooting

shooting_club_standard_stats = pd.read_csv(r"C:\Users\salma\Downloads\Shooting_Standard_Stats.csv")
shooting_domestic_league = pd.read_csv(r"C:\Users\salma\Downloads\League_Shooting_Standard_Stats_and_Summary.csv")
shooting_domestic_cup = pd.read_csv(r"C:\Users\salma\Downloads\Domestic_Cups_Shooting_Standard_Stats_and_Summary.csv")
shooting_international_cups = pd.read_csv(r"C:\Users\salma\Downloads\European_International_Cups_Shooting_Standard_Stats.csv")
shooting_national_team = pd.read_csv(r"C:\Users\salma\Downloads\International_England_Shooting_Standard_Stats.csv")

In [16]:
club_standard_stats = club_standard_stats.copy()
domestic_league = domestic_league.copy()
domestic_cup = domestic_cup.copy()
international_cups = international_cups.copy()
national_team = national_team.copy()

club_standard_stats["Competition_Type"] = "Club"
domestic_league["Competition_Type"] = "Domestic League"
domestic_cup["Competition_Type"] = "Domestic Cup"
international_cups["Competition_Type"] = "International Cup"
national_team["Competition_Type"] = "National Team"

In [17]:
shooting_club_standard_stats["Competition_Type"] = "Club"
shooting_domestic_league["Competition_Type"] = "Domestic League"
shooting_domestic_cup["Competition_Type"] = "Domestic Cup"
shooting_international_cups["Competition_Type"] = "International Cup"
shooting_national_team["Competition_Type"] = "National Team"

In [18]:
standard_stats = pd.concat(
    [
        club_standard_stats,
        domestic_league,
        domestic_cup,
        international_cups,
        national_team
    ],
    ignore_index=True
)

In [19]:
standard_stats.shape

(107, 24)

In [20]:
standard_stats.head()

,Season,Age,Squad,Country,Comp,LgRank,MP,Starts,Min,90s,...,PK,PKatt,CrdY,CrdR,Gls_90,Ast_90,G+A_90,G-PK_90,G+A-PK_90,Competition_Type
0,2019-2020,16,Birmingham City,ENG,2. Championship,20th,41,32,2694,29.9,...,0,0,7,0,0.13,0.07,0.20,0.13,0.20,Club
1,2020-2021,17,Dortmund,GER,1. Bundesliga,3rd,29,19,1697,18.9,...,0,0,6,1,0.05,0.16,0.21,0.05,0.21,Club
2,2021-2022,18,Dortmund,GER,1. Bundesliga,2nd,32,32,2790,31.0,...,0,0,9,0,0.10,0.26,0.35,0.10,0.35,Club
3,2022-2023,19,Dortmund,GER,1. Bundesliga,2nd,31,30,2691,29.9,...,1,0,8,1,0.27,0.13,0.40,0.23,0.37,Club
4,2023-2024,20,Real Madrid,ESP,1. La Liga,1st,28,27,2315,25.7,...,1,1,5,1,0.74,0.23,0.97,0.70,0.93,Club

In [21]:
shooting = pd.concat(
    [
        shooting_club_standard_stats,
        shooting_domestic_league,
        shooting_domestic_cup,
        shooting_international_cups,
        shooting_national_team
    ],
    ignore_index=True
)

In [22]:
shooting.shape

(82, 18)

In [23]:
shooting["Competition_Type"].value_counts()

Competition_Type
Club                 31
National Team        16
Domestic Cup         15
Domestic League      10
International Cup    10
Name: count, dtype: int64

In [24]:
standard_stats[
    ["Season", "Squad", "Comp", "Competition_Type"]
].sort_values(["Season", "Competition_Type"])

,Season,Squad,Comp,Competition_Type
0,2019-2020,Birmingham City,2. Championship,Club
36,2019-2020,Birmingham City,EFL Cup,Domestic Cup
37,2019-2020,Birmingham City,FA Cup,Domestic Cup
18,2019-2020,Birmingham City,2. Championship,Domestic League
82,2020,England,Friendlies (M),National Team
...,...,...,...,...
104,UEFA Euro (2 Seasons),NaN,NaN,National Team
106,UEFA Euro qual. (1 Season),NaN,NaN,National Team
102,UEFA Nations League (3 Seasons),NaN,NaN,National Team
105,WCQ (2 Seasons),NaN,NaN,National Team
103,World Cup (2 Seasons),NaN,NaN,National Team

In [25]:
shooting[
    ["Season", "Squad", "Comp", "Competition_Type"]
].sort_values(["Season", "Competition_Type"])

       Season            Squad             Comp   Competition_Type
0   2019-2020  Birmingham City  2. Championship               Club
1   2019-2020  Birmingham City          EFL Cup               Club
2   2019-2020  Birmingham City           FA Cup               Club
41  2019-2020  Birmingham City          EFL Cup       Domestic Cup
42  2019-2020  Birmingham City           FA Cup       Domestic Cup
..        ...              ...              ...                ...
65  2026-2027      Real Madrid  1. Champions Lg  International Cup
55  7 Seasons              NaN        6 Leagues       Domestic Cup
40  8 Seasons              NaN        3 Leagues    Domestic League
54    Summary              NaN              NaN       Domestic Cup
39    Summary              NaN              NaN    Domestic League

[82 rows x 4 columns]

In [28]:
standard_stats.groupby(
    ["Season", "Competition_Type"]
).size()

Season                           Competition_Type
2019-2020                        Club                1
                                 Domestic Cup        2
                                 Domestic League     1
2020                             National Team       1
2020-2021                        Club                1
                                                    ..
UEFA Euro (2 Seasons)            National Team       1
UEFA Euro qual. (1 Season)       National Team       1
UEFA Nations League (3 Seasons)  National Team       1
WCQ (2 Seasons)                  National Team       1
World Cup (2 Seasons)            National Team       1
Length: 93, dtype: int64

In [27]:
shooting.groupby(
    ["Season", "Competition_Type"]
).size()

Season     Competition_Type
2019-2020  Club                 3
           Domestic Cup         2
           Domestic League      1
2020       National Team        1
2020-2021  Club                 4
           Domestic Cup         2
           Domestic League      1
           International Cup    1
2021       National Team        2
2021-2022  Club                 5
           Domestic Cup         2
           Domestic League      1
           International Cup    2
2022       National Team        3
2022-2023  Club                 3
           Domestic Cup         1
           Domestic League      1
           International Cup    1
           National Team        1
2023       National Team        1
2023-2024  Club                 4
           Domestic Cup         2
           Domestic League      1
           International Cup    1
2024       National Team        3
2024-2025  Club                 5
           Domestic Cup         2
           Domestic League      1
           International Cup    2
           National Team        1
2025       Club                 1
           International Cup    1
           National Team        1
2025-2026  Club                 4
           Domestic Cup         2
           Domestic League      1
           International Cup    1
2026       National Team        3
2026-2027  Club                 2
           Domestic League      1
           International Cup    1
7 Seasons  Domestic Cup         1
8 Seasons  Domestic League      1
Summary    Domestic Cup         1
           Domestic League      1
dtype: int64

In [29]:
standard_stats.isna().sum()

Season               0
Age                 41
Squad               37
Country             78
Comp                49
LgRank              62
MP                   0
Starts               0
Min                  1
90s                  1
Gls                  1
Ast                  1
G+A                  1
G-PK                 1
PK                   1
PKatt                1
CrdY                 1
CrdR                 1
Gls_90               1
Ast_90               1
G+A_90               1
G-PK_90              1
G+A-PK_90            1
Competition_Type     0
dtype: int64

In [30]:
standard_stats.dtypes

Season              str
Age                 str
Squad               str
Country             str
Comp                str
LgRank              str
MP                  str
Starts              str
Min                 str
90s                 str
Gls                 str
Ast                 str
G+A                 str
G-PK                str
PK                  str
PKatt               str
CrdY                str
CrdR                str
Gls_90              str
Ast_90              str
G+A_90              str
G-PK_90             str
G+A-PK_90           str
Competition_Type    str
dtype: object

In [31]:
shooting.dtypes

Season                 str
Age                 object
Squad                  str
Country                str
Comp                   str
90s                 object
Gls                 object
Sh                  object
SoT                 object
SoT%                object
Sh_90               object
SoT_90              object
G_Sh                object
G_SoT               object
PK                  object
PKatt               object
Competition_Type       str
LgRank                 str
dtype: object

In [32]:
numeric_cols = [
    "Age", "MP", "Starts", "Min", "90s",
    "Gls", "Ast", "G+A", "G-PK", "PK", "PKatt",
    "CrdY", "CrdR",
    "Gls_90", "Ast_90", "G+A_90",
    "G-PK_90", "G+A-PK_90"
]

standard_stats[numeric_cols] = standard_stats[numeric_cols].apply(
    pd.to_numeric,
    errors="coerce"
)

In [33]:
shooting_numeric_cols = [
    "Age", "90s", "Gls", "Sh", "SoT",
    "SoT%", "Sh_90", "SoT_90",
    "G_Sh", "G_SoT", "PK", "PKatt"
]

shooting[shooting_numeric_cols] = shooting[shooting_numeric_cols].apply(
    pd.to_numeric,
    errors="coerce"
)

In [34]:
keys = ["Season", "Squad", "Comp", "Competition_Type"]

standard_stats.duplicated(keys).sum()

np.int64(0)

In [35]:
shooting.duplicated(keys).sum()

np.int64(0)

In [36]:
player_stats = standard_stats.merge(
    shooting,
    on=["Season", "Squad", "Comp", "Competition_Type"],
    how="left",
    suffixes=("", "_shooting")
)

### Start percentage

In [37]:
standard_stats["Start_Rate"] = (
    standard_stats["Starts"] / standard_stats["MP"]
)

### Minutes per match

In [38]:
standard_stats["Minutes_per_Match"] = (
    standard_stats["Min"] / standard_stats["MP"]
)

### Penalty conversion

In [39]:
standard_stats["Penalty_Conversion"] = (
    standard_stats["PK"] /
    standard_stats["PKatt"].replace(0, pd.NA)
)

# Player performance over time

## Goals per 90